#!/usr/bin/env bash
# This script displays all active IPv4 IP addresses on the machine, including localhost

ip -4 addr show scope global | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
ip -4 addr show scope host | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
